title: "Kaushal Dasika"
description: "Technology Policy, Governance, and Data Analysis"

url: "https://kaushdasika.github.io"
baseurl: "/PolicyWork"

theme: minima

include:
  - pdfs

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
